time_scale: 5 # seconds between actions
chain_min: -900  # 1000 ~ 90 degrees
chain_max: 900
chain_speed: 5000
chain_time_per_1000: 12.25  # measured value in seconds, assuming `chain_speed`
gun_min: 0
gun_max: 2000
gun_speed: 900
gun_max_per_move: 50  # ~3s max duration
gun_time_per_1000: 67  # measured value in seconds, assuming `gun_speed`
wait_for_camera_time: 30  # time to wait until we make a random move because camera offline

detectron_model: faster_rcnn_fbnetv3a_dsmask_C4.yaml
detectron_person_class: 0  # COCO 2017 used in model
# Downscale image for person detection. 224, 320 takes ~10s/image, 112, 160 takes ~5s/image
detectron_min_size: 112
detectron_max_size: 160
detectron_confidence_threshold: 0.5  # Ignore detections with lower confidence.
